## PyTorch vs NumPy

In [2]:
import torch 
import numpy as np

In [3]:
a = np.array([1,2])
b = np.array([8,9])
c = a+ b
c

array([ 9, 11])

In [7]:
#Adding the same arrays with PyTorch looks like this:
a = torch.tensor([1,2])
b = torch.tensor([8,9])
c = a+b
c

tensor([ 9, 11])

In [19]:
#Fortunately, you can go from NumPy to PyTorch and vice versa
a = torch.tensor([1,2])
a.numpy()

array([1, 2])

In [30]:
a = np.array([1,2])
torch.from_numpy(a)

tensor([1, 2])

## Tensors

In [20]:
#You can create a tensor from integers:
torch.tensor([[1,2], [2,1]])

tensor([[1, 2],
        [2, 1]])

In [21]:
#You can create a tensor from floats:
torch.FloatTensor([[1,2],[2,1]])

tensor([[1., 2.],
        [2., 1.]])

In [22]:
#Or define the type like so:
torch.tensor([[1,2], [2,1]], dtype = torch.bool)

tensor([[True, True],
        [True, True]])

In [23]:
#you can create a matrix with random numbers like this:
torch.rand(3,2)

tensor([[0.5272, 0.5737],
        [0.3331, 0.3759],
        [0.5579, 0.6327]])

In [24]:
#Or one full of ones:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [25]:
#PyTorch has a variety of useful operations:
x = torch.tensor([[2,3], [1,2]])
print(x)
print(f'sum: {x.sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 8


In [26]:
#Get the transpose of a 2-D tensor:
x.t()

tensor([[2, 1],
        [3, 2]])

In [27]:
#Get the shape of each dimension:
x.size()

torch.Size([2, 2])

In [28]:
#Generally, performing some operation creates a new Tensor:

y = torch.tensor([[2,2], [5,1]])
z = x.add(y)
z

tensor([[4, 5],
        [6, 3]])

In [29]:
#But you can do it in-place:
x.add_(y)

tensor([[4, 5],
        [6, 3]])

## Running on GPU

In [35]:
#Let’s start by checking if GPU is available:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [36]:
#Let’s store a Tensor on it:
x = torch.tensor([[2,3], [1,2]])
x.to(device)

tensor([[2, 3],
        [1, 2]], device='cuda:0')

In [38]:
#Notice that our Tensor is now on device cuda:0. What can we do with it? Pretty much everything
x = x.to(device)
y = torch.tensor([[2,2],[5,1]])
y = y.to(device)
x.add(y)

tensor([[4, 5],
        [6, 3]], device='cuda:0')